[tool.poetry]
name = "pydantic-advanced"
version = "0.1.0"
description = ""
authors = ["Dan <dan@apix.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
